---
- name: "Check for tftp installation"
  stat:
    path: '{{ tftp_install_dir }}/tftp.py'
  changed_when: false
  register: tftp_install

- when: not tftp_install.stat.exists or tftp_force_install|bool
  block:
    - name: "Install requierements"
      package:
        name: "libpq-dev"
        state: present

    - name: "Install pip package"
      pip:
        name:
          - requests
          - fbtftp
          - jinja2
          - psycopg2-binary
        state: present
        executable: pip3

    - name: "Ensure install directory exists"
      file:
        path: '{{ tftp_install_dir }}'
        state: directory
        mode: 0755

- name: "Copy simplehttp.py"
  template:
    src: 'simplehttp.py.j2'
    dest: '{{ tftp_install_dir }}/simplehttp.py'
    mode: '0755'

- name: "Copy tftp.py"
  template:
    src: 'tftp.py.j2'
    dest: '{{ tftp_install_dir }}/tftp.py'
    mode: '0755'

- name: "Create systemd for simple http"
  template:
    src: http.service.j2
    dest: /etc/systemd/system/http.service
    mode: 0644
  notify: "restart http"

- name: "Create systemd for tftp"
  template:
    src: tftp.service.j2
    dest: /etc/systemd/system/tftp.service
    mode: 0644
  notify: "restart tftp"

- name: "Copy httproot files (ftp content)"
  copy:
    src: '{{ tftp_httproot_files }}'
    dest: '/'
    mode: '0644'

- name: Start http.service
  service:
    name: http
    state: started
    enabled: true
    daemon_reload: true

- name: Start tftp.service
  service:
    name: tftp
    state: started
    enabled: true
    daemon_reload: true
